name: teraform

env:
   Message : ./instance/example

on:
  workflow_dispatch:

jobs:
  assignment:
    runs-on: ubuntu-latest
    env:
        AWS_ACCESS_KEY_ID:  ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
        AWS_SESSION_TOKEN: ${{secrets.AWS_SESSION_TOKEN}}
    steps:
      - name: Checkout
        uses: actions/checkout@v3    
        
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      
      - name: Terraform initializing 
        id: init
        run: terraform init
        working-directory: ${{ env.Message }}

      - name: Terraform plan
        id: plan
        run: terraform plan -no-color
        working-directory: ${{ env.Message }}  
      
      - name: Terraform destroy 
        id: destroy
        run: terraform destroy -auto-approve
        working-directory: ${{ env.Message }}
      