name : Terraform actions

env: 

  Message: Jhansigithub_Actions

on:

  push:
    branches: ["main", "master"]
  pull_request:
    branches: ["main" , "master"]

  workflow_dispatch:

jobs:

  terraform:
    name: 'terraform fmt'
    runs-on : ubuntu-latest
    
    env:
      AWSACESSKEY: ${{secrets.AWSACESSKEY}}
      SECRETACESS : ${{secrets.SECRETACESS}}
      SESSIONTOKEN : ${{secrets.SESSIONTOKEN}}
      

    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: setu 
        uses: hashicorp/setup-terraform@v2
        with :
          terraform_version: 1.1.7

      - name: Inatilize
        id: init
        run : terraform init
        working-directory : "./instance/example"

      - name: Format
        id: fmt
        run: terraform fmt
        working-directory : "./instance/example"

      - name: Validate
        id: validate
        run: terraform validate
        working-directory : "./instance/example"

         
      - name: plan
        id: plan
        run: terraform plan
        working-directory : "./instance/example"






