name: JhansiGithubactions

env:
   Message : ./instance/example

on:
  push:
    branches: [ "main" , "master" ]
  pull_request:
    branches: [ "main" , "master" ]
  workflow_dispatch:

jobs:
  terraform-assignment:
    runs-on: ubuntu-latest
    env:
        AWSACESSKEY:  ${{secrets.AWSACESSKEY}}
        SECRETACESS : ${{secrets.SECRETACESS}}
        SESSIONTOKEN : ${{secrets.SESSIONTOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3    
        
      - name: Setup Terraform 
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.7
      
      - name: Terraform fmt
        id: fmt
        run: terraform fmt
        working-directory: ${{ env.Message }}
        continue-on-error: true  

      - name: Terraform initializing 
        id: init
        run: terraform init
        working-directory: ${{ env.Message }}

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: ${{ env.Message}}

      - name: Terraform plan
        id: plan
        if: github.event_name == 'push'
        run: terraform plan -no-color
        working-directory: ${{ env.Message }}
        continue-on-error: true